#!/usr/bin/env bash
# manages manage_my_process

case "$1" in
	start)
		./manage_my_process &
		echo $! > /tmp/my_process.pid
		echo "manage_my_process started"
		;;
	stop)
		kill "$(cat /tmp/my_process.pid)"
		rm /tmp/my_process.pid
		echo "manage_my_process stopped"
		;;
	restart)
		kill "$(cat /tmp/my_process.pid)"
		rm /tmp/my_process.pid
		./manage_my_process &
		echo $! > /tmp/my_process.pid
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
